### ISSUE TITLE
Neural Networks with Few Multiplications

### ISSUE THREAD

**Issue by bhack** [MatthieuCourbariaux/BinaryConnect#1]
Do you will include code also for http://arxiv.org/abs/1510.03009?

**Comment by MatthieuCourbariaux** [comment]
The code for "Neural Networks with Few Multiplications" ( http://arxiv.org/abs/1510.03009 )
is available at https://github.com/hantek/binary_conv .
The documentation is not very extensive (yet). Hantek (Zhouhan Lin) is currently working on it.

Edit: 
The code is now available at https://github.com/hantek/BinaryConnect and the documentation is more extensive (see Hantek comment below).

**Comment by bhack** [comment]
Thanks

**Comment by hantek** [comment]
Hi bhack,

Just to let you know that we have released the code for http://arxiv.org/abs/1510.03009 . Please check it here: https://github.com/hantek/BinaryConnect
